### ISSUE TITLE
idk, detecting as a Virus

### ISSUE THREAD

**Issue by Vennntox** [GTNewHorizons/NotEnoughIds#11]
![Unbenanntdsa](https://github.com/GTNewHorizons/NotEnoughIds/assets/31446572/b8e29445-c332-406f-a142-24c312c5b524)

**Comment by Caedis** [comment]
Report to Microsoft as a false positive  

https://www.virustotal.com/gui/file/c4a744efff36a1a967eb8812b228a0c11ae03e894ceac314e81c3fe75d6fdc87?nocache=1
