### ISSUE TITLE
Add attribution to EndlessIDs (code copied without any license notice)

### ISSUE THREAD

**Issue by FalsePattern** [GTNewHorizons/NotEnoughIds#13]
The [ChunkProviderSuperPatcher](https://github.com/GTNewHorizons/NotEnoughIds/blob/8124b6f19d0fa5e6e668941c0a8f4d7e68c3809a/src/main/java/com/gtnewhorizons/neid/asm/transformer/ChunkProviderSuperPatcher.java) class is a direct copy of the [EndlessIDs ChunkProviderSuperPatcher](https://github.com/GTMEGA/EndlessIDs/blob/master/src/main/java/com/falsepattern/endlessids/asm/transformer/ChunkProviderSuperPatcher.java) with very minor funcional changes, and basic code reformatting.

As per the EndlessIDs license, if you use parts of the codebase, you must include a verbatim copy of the original license as per the GPLv3.0 sections 5-b, 5-c, and 7-b, as well as in the compiled jar files as per section 6.

```
EndlessIDs

Copyright (C) 2022-2023 FalsePattern
All Rights Reserved

The above copyright notice, this permission notice and the words "MEGA"
shall be included in all copies or substantial portions of the Software.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```

**Comment by Cleptomania** [comment]
This class has been fully removed.
