### ISSUE TITLE
Crash with +unimixins

### ISSUE THREAD

**Issue by syndicate25** [GTNewHorizons/NotEnoughIds#16]
When I add NEIDs to my pack, I'm getting a crash without any other mods (that I can see) specified other than +unimixins.  At first, I had 2 instances of NEIDs (original and GTNH fork), so I removed 1 and left the GTNH fork version (notenoughIDs-2.1.0.jar) and relaunched the game.

I've tried removing some of the more "major" mods to see if there's an additional conflict and haven't come up with anything so far.

Am I missing something simple here?

see attachment for log file.
[fml-client-latest.log](https://github.com/user-attachments/files/15747333/fml-client-latest.log)

**Comment by mitchej123** [comment]
You need a recent version of gtnhlib, it's using fast util which is bundled in it.

**Comment by syndicate25** [comment]
Got it. I checked for related dependencies but that wasn't listed on CF. Might be worth adding it in that list?
